### ISSUE TITLE
Tailwind v1.0

### ISSUE THREAD

**Issue by mikemand** [javisperez/tailwindcolorshades#6]
Hi Javis,

I'm opening this in advance of Tailwind's v1.0 release so we might be able to get a jump on updating before they do a stable v1.0 release.

Colors changed from being named (e.g.: `color-darker`, `color-lighter`, etc.) to a numeric system. There are also now 2 new shades, apparently falling between `darkest` and `darker` (and `lightest` and `lighter`). Here is Adam's suggested replacement guide for colors:

| Old | New |
| --- | --- |
| {color}-darkest | {color}-900 |
| {color}-darker | {color}-800 |
| {color}-dark | {color}-600 |
| {color} | {color}-500 |
| {color}-light | {color}-400 |
| {color}-lighter | {color}-200 |
| {color}-lightest | {color}-100 |

It also looks like they reversed the order of the colors again, going from [lightest to darkest](https://github.com/tailwindcss/tailwindcss/blob/v1.0.0-beta.3/stubs/defaultConfig.stub.js).

I can reverse the colors again since I did it once before, but I am not sure how to calculate the new scale of shades. I don't quite understand how you're doing it now, so I'm not sure what needs to change to insert the new shades.

**Comment by javisperez** [comment]
Hey @mikemand 👋 thank you so much for this issue and your amazing update! I've been really busy and unable to check this repo, so, sorry for the long reply 🙇.

I'll have a look now to your PR which at first instance seems pretty good! and might merge it instantly. But before i deploy it to master, gonna make a few changes to add the whole set of new colors (will add an option to choose what version to generate instead of just supporting 1.0, also will add the pending new color set between darker and darkest / lighter and lightest).

Thanks again!

**Comment by mikemand** [comment]
Awesome, thanks @javisperez!

**Comment by admench** [comment]
Great work @javisperez and @mikemand ! Thank you!

**Comment by javisperez** [comment]
Thanks, @mikemand and @admench 🎉 !
